name: build

on:
  pull_request:
    branches: [release, preview, dev]
  push:
    branches: [release, preview, dev]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # avoid shallow clone for Nerdbank.GitVersioning
          fetch-depth: 0
      - uses: dotnet/nbgv@master
        id: nbgv
        with:
          setAllVars: true
          setCommonVars: true
      - run: "echo 'SemVer2: ${{ steps.nbgv.outputs.SemVer2 }}'"
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Build Tool Info
        run: dotnet build EconomyMonitor.sln
