name: Release--win-x64
on: 
  push:
    branches: [release]
    tags: 
        - "v*.*"
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # avoid shallow clone for Nerdbank.GitVersioning
          fetch-depth: 0
      - uses: dotnet/nbgv@master
        id: nbgv
        with:
          setAllVars: true
          setCommonVars: true
      - run: "echo 'SemVer2: ${{ steps.nbgv.outputs.SemVer2 }}'"
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Publish Win-x64
        run: dotnet publish src/EconomyMonitor.Wpf/ -c Release -r win-x64 -o artifacts/publish/win-x64 --self-contained
      - name: Post Publish
        run: ren "artifacts/publish/win-x64/EconomyMonitor.Wpf.exe" "Economy Monitor--win-x64--${{ steps.nbgv.outputs.SemVer2 }}.exe"
      - name: Archive
        run: tar.exe -vacf "Economy Monitor--win-x64--${{ steps.nbgv.outputs.SemVer2 }}.zip" -C "artifacts/publish/win-x64" "*.*"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.nbgv.outputs.SemVer2 }}
          prerelease: false
          files: "*.zip"
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "Economy Monitor--win-x64--${{ steps.nbgv.outputs.SemVer2 }}.zip"
          asset_name: "Economy Monitor--win-x64--${{ steps.nbgv.outputs.SemVer2 }}.zip"
          asset_content_type: application/zip
